[package]
name = "minidump-debugger"
version = "0.3.3"
edition = "2021"
description = "an experimental GUI for inspecting minidumps with rust-minidump"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Gankra/minidump-debugger"
keywords = ["minidump", "debugger", "rust-minidump"]
categories = ["development-tools"]
authors = ["Aria Beingessner <a.beingessner@gmail.com>"]

[package.metadata.wix]
upgrade-guid = "C2649249-9DC8-47EC-855B-CD4BD8444D1D"
path-guid = "A68C9CFB-7058-42EA-ADF1-09F5FAA40034"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["inline"]

# Use the inline frame fields introduced in rust-minidump 0.14.0
inline = []

[dependencies]
eframe = "0.18.0"
egui = "0.18.1"
egui_extras = "0.18.0"
memmap2 = "0.5.5"
breakpad-symbols = { version = "0.18.0" }
minidump = { version = "0.18.0" }
minidump-common = { version = "0.18.0" }
minidump-processor = { version = "0.18.0", features = ["http", "dump_syms", "debuginfo"] }
minidump-unwind = { version = "0.18.0", features = ["debuginfo", "http", "swift"] }
num-traits = "0.2.15"
rfd = "0.9.1"
tempfile = "3.3.0"
tokio = { version = "1.20.0", features = ["time", "macros"] }
tracing = { version = "0.1.34", features = ["log"] }
tracing-subscriber = "0.3.14"
linked-hash-map = "0.5.6"
clap = { version = "3.2.15", features = ["derive"] }

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.4.0-prerelease.2"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "powershell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-pc-windows-msvc"]
# Publish jobs to run in CI
pr-run-mode = "plan"

[workspace.metadata.dist.dependencies.apt]
libclang-dev = "*"
libgtk-3-dev = "*"
libxcb-render0-dev = "*"
libxcb-shape0-dev  = "*"
libxcb-xfixes0-dev = "*"
libxkbcommon-dev = "*"
libssl-dev = "*"

